### ISSUE TITLE
JSON::ParserError: 765: unexpected token at ''

### ISSUE THREAD

**Issue by sapran** [michenriksen/aquatone#10]
I have the following error message appearing for every URL I try to grab by aquatone-gather:

``JSON::ParserError: 765: unexpected token at ''``

**Comment by michenriksen** [comment]
Hey @sapran, this issue is related to running the tool in an environment with no graphical desktop session. 

I don't think there is much I can do about this, but I will add better handling of the error to inform the user what to do.
