### ISSUE TITLE
io domain names are not recongnized

### ISSUE THREAD

**Issue by yassineaboukir** [michenriksen/aquatone#100]
Apprently, websites with io TLD is not recognized and considered invalid domain name.
```
$ aquatone-discover --domain https://example.io/ --threads 25
https://example.io/ doesn't look like a valid domain name.
```

**Comment by EdOverflow** [comment]
`https://example.io/` is not a recognised domain name. You have to specify it as a FQDN (`aquatone-discover --domain example.io`). This is the case for all domains no matter the TLD. 

@michenriksen, maybe you could consider stripping the protocol and path if someone includes it by accident like @yassineaboukir did here?

**Comment by yassineaboukir** [comment]
You are actually right! I am not sure how I missed this but I agree that it would be good to parse the URL and only take the hostname just in case someone like me accidentally included the URL scheme.
