### ISSUE TITLE
Incompatability Error

### ISSUE THREAD

**Issue by mhamed366** [michenriksen/aquatone#102]
Hii,
i faced this issue under mac and i can't solve it,
i tested solutions suggested on the previous issues but nothing worked under mac, thanks

Incompatability Error:
Nightmarejs must be run on a system with a graphical desktop session (X11)

**Comment by EdOverflow** [comment]
The README.md states the following:

> IMPORTANT: AQUATONE's screenshotting capabilities depend on being run on a system with a graphical desktop environment. It is strongly recommended to install and run AQUATONE in a Kali linux virtual machine. I will not provide support or bug fixing for other systems than Kali Linux.
