### ISSUE TITLE
Aborted (Core Dumped) while running aquatone-scan with --ports huge on starbucks.com

### ISSUE THREAD

**Issue by quinl** [michenriksen/aquatone#105]

**Comment by sa7mon** [comment]
Can you post a screenshot of the error after it happens? I've scanned starbucks without issues.

**Comment by sa7mon** [comment]
@ojaschauhan44 Have you tried the `xvfb-run` solution that's been posted in numerous other issues filed in this project?

**Comment by ojaschauhan44** [comment]
Yes i tried the solution but still same error.
There is even a issue thread for the same but no solution
