### ISSUE TITLE
Incompatability Error: Nightmarejs must be run on a system with a graphical desktop session (X11)

### ISSUE THREAD

**Issue by ojaschauhan44** [michenriksen/aquatone#112]
Still not able to find a solution for this one... tried everything...
==>> DEBUG=nightmare xvfb-run ... Doesnt work...

**Comment by ojaschauhan44** [comment]
solved the problem. its with electrons postscript

**Comment by x-f1v3** [comment]
Great

**Comment by x-f1v3** [comment]
Great  thank you very much
