### ISSUE TITLE
about JSON::ParserError: 765: unexpected token at ''

### ISSUE THREAD

**Issue by super5hunz1** [michenriksen/aquatone#12]
Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016

[root@install ~]# node -v
v6.10.3

aquatone-discover and aquatone-scan is success.

but aquatone-gether print 
**Failed: https://xxx/ (xxx) - JSON::ParserError: 765: unexpected token at ''** 
how fix this ?
thank reply :)

**Comment by hydhyd** [comment]
Same issue:

➜  ~ node -v
v8.1.2

It was suggested by author that it has to be ran from within a "graphical desktop session", e.g. an X11 session?

Running from a Gnome Terminal here, so unless it means something else entirely, I'm at a loss.

**Comment by super5hunz1** [comment]
thank u hydhyd.
i try use graphical desktop session :D

**Comment by super5hunz1** [comment]
i try use vnc connect :)
but can't work
![sb](https://user-images.githubusercontent.com/29603143/27417458-1b5ea180-5747-11e7-9827-e2032a58e0c5.png)
