### ISSUE TITLE
port scan failed

### ISSUE THREAD

**Issue by jinyu00** [michenriksen/aquatone#126]
The program report the target port is closed
![](https://ws1.sinaimg.cn/large/006daSSqgy1fx1tbgjfnqj30w80eet9p.jpg)

but I can nc to the 80 port
![](https://ws1.sinaimg.cn/large/006daSSqgy1fx1tcpu7svj30tw0afjry.jpg)

The targets
```
www.nuaa.edu.cn
blog.hac425.top

```

**Comment by michenriksen** [comment]
Try to increase the port scanning timeout with `-scan-timeout`. Default is 50ms, but try 100 or 150.
