### ISSUE TITLE
Difficulty

### ISSUE THREAD

**Issue by sbakhour** [michenriksen/aquatone#127]
Hello @michenriksen,

I am having lot of difficulties using the new aquatone. I can’t run it. I tried to read the readme manual & spent the whole night yesterday without any luck.
Maybe it is my mistake & I misunderstood how the new version works. I was using perfectly the older versions but I don’t know how to run commands in the new one. As per what I understood, it is one command instead of discover, gather, scan & takeover; but still I don’t know how to manage to use the new command. Could you please help by giving one example how to scan a site (example.com) & gather all data ? I really appreciate your support.  One last thing, is it required to remove the previous version to use the new one ? If yes then can you provide the steps to do it? If no then can you show how to use the new one ?
I am using Kali Linux latest build.
Thank you,
Sami

**Comment by michenriksen** [comment]
The new aquatone works by having output containing hosts, URLs or IPs piped to it. Please see the [Usage Examples](https://github.com/michenriksen/aquatone#usage-examples) of the README.
