### ISSUE TITLE
Aquatone still fails to work against targets with invalid SSL certs.

### ISSUE THREAD

**Issue by eur0pa** [michenriksen/aquatone#131]
Aquatone will _not_ grab a screenshot of any target whose SSL certificate is expired, doesn't match the correct hostname, or is otherwise invalid.

**Steps to reproduce**:
1. run the following command using any of the proposed tests at https://badssl.com:
```
❯ echo 'https://expired.badssl.com' | aquatone
❯ echo 'https://wrong.host.badssl.com' | aquatone
❯ echo 'https://self-signed.badssl.com' | aquatone
...
```
2. observe how the screenshot hasn't been taken

**Comment by michenriksen** [comment]
Sorry, I am still unable to reproduce the problem you are experiencing:

```
$ cat /tmp/badssl.txt | aquatone -out /tmp/badssl
aquatone v1.4.0 started at 2018-11-17T16:33:34+01:00

Targets    : 3
Threads    : 4
Ports      : 80, 443, 8000, 8080, 8443
Output dir : /tmp/badssl

https://wrong.host.badssl.com: 200 OK
https://expired.badssl.com: 200 OK
https://self-signed.badssl.com: 200 OK
https://expired.badssl.com: screenshot successful
https://wrong.host.badssl.com: screenshot successful
https://self-signed.badssl.com: screenshot successful

Clustering similar sites... done
Generating HTML report... done

Time:
 - Started at  : 2018-11-17T16:33:34+01:00
 - Finished at : 2018-11-17T16:33:38+01:00
 - Duration    : 3s

Requests:
 - Successful : 3
 - Failed     : 0

 - 2xx : 3
 - 3xx : 0
 - 4xx : 0
 - 5xx : 0

Screenshots:
 - Successful : 3
 - Failed     : 0

Wrote HTML report to: /tmp/badssl/aquatone_report.html
```
![badssl](https://user-images.githubusercontent.com/304361/48662751-dbdcd480-ea86-11e8-9fc3-a5d4bc5792e4.png)

**Comment by eur0pa** [comment]
Both **Chrome** and **Chromium**, for me:

```
aquatone v1.4.0 started at 2018-11-17T16:56:57+01:00

Targets    : 1
Threads    : 4
Ports      : 80, 443, 8000, 8080, 8443
Output dir : .

https://self-signed.badssl.com: 200 OK

Clustering similar sites... done
Generating HTML report... done

Time:
 - Started at  : 2018-11-17T16:56:57+01:00
 - Finished at : 2018-11-17T16:56:58+01:00
 - Duration    : 1s

Requests:
 - Successful : 1
 - Failed     : 0

 - 2xx : 1
 - 3xx : 0
 - 4xx : 0
 - 5xx : 0

Screenshots:
 - Successful : 0
 - Failed     : 0

Wrote HTML report to: aquatone_report.html
```

**Comment by eur0pa** [comment]
There seems to be an issue with how `stdin` is being handled against different Chrome browsers

condition | setup | outcome
--|--|--
`echo $target` | chrome latest | **no** screenshot taken
`echo $target` | chromium latest | **no** screenshot taken
`echo $target` | chromium 61 | **no** screenshot taken
`cat targets.txt` | chrome latest | screenshot **timeout**
`cat targets.txt` | chromium latest | screenshot **successful**
`cat targets.txt` | chromium 61 | **blank** screenshot

**Comment by panchocosil** [comment]
Amazing tool! Thanks michenriksen! I'm having the same issue here. What exact version of chromium is working?  I'm using Chromium 70.0.3538.77 Built on Ubuntu , running on Ubuntu 16.04.

**Comment by michenriksen** [comment]
I am using Chromium 72.0.3604.0 and works perfectly with the binary release for Mac. Are you all using the precompiled release binary or did you compile it yourself?

**Comment by eur0pa** [comment]
@michenriksen compiled from source

**Comment by einfallstoll** [comment]
@michenriksen latest binary + Chromium 70.0.3538.102

**Comment by michenriksen** [comment]
@einfallstoll can you try to download the [latest Chromium](https://download-chromium.appspot.com/) and run aquatone with:

    echo "https://expired.badssl.com https://wrong.host.badssl.com https://self-signed.badssl.com" | aquatone

**Comment by einfallstoll** [comment]
@michenriksen yhea, that did the trick

**Comment by panchocosil** [comment]
Thanks @michenriksen now using Chromium 72.0.3604.0 and is working perfect. cheers!
