### ISSUE TITLE
Aquatone-discover

### ISSUE THREAD

**Issue by B4RD4k** [michenriksen/aquatone#135]
Hi, 
i saw the version upgrade commit and i have question?
1. how do i start the discover mechanism from the previous ruby version? did you shut it down?

**Comment by michenriksen** [comment]
Yes, DNS enumeration is no longer part of Aquatone as other tools are already doing a good job at that. I can recommend [Amass](https://github.com/OWASP/Amass) and [Subfinder](https://github.com/subfinder/subfinder) for this. You can easily feed the output from these tools into Aquatone for scanning and screenshotting.
