### ISSUE TITLE
I have a presumptuous request 

### ISSUE THREAD

**Issue by Jumbo-WJB** [michenriksen/aquatone#137]
First of all, thank you for writing such a good tool, but I have a presumptuous request now, I hope the go version of the aquatone can have the ruby version of the aquatone which can be combined url (such as https://www .google. Com) The ability to save to a file.
tks!

**Comment by michenriksen** [comment]
Hi there! Do you mean a feature to have aquatone write the responsive URLs to a file?

**Comment by Jumbo-WJB** [comment]
yes.sorry to bother you!

**Comment by michenriksen** [comment]
This feature will land pretty soon from this [pull request](https://github.com/michenriksen/aquatone/pull/133) . Stay tuned! :)

**Comment by michenriksen** [comment]
This is now added in version [1.4.2](https://github.com/michenriksen/aquatone/releases/tag/v1.4.2)
