### ISSUE TITLE
Inconsistent results when using -ports

### ISSUE THREAD

**Issue by lazydruidr** [michenriksen/aquatone#138]
When using -ports option aquatone produces inconsistent results.

**echo "www.google.com" | aquatone -ports '443' -debug**

aquatone v1.4.1 started at 2018-11-19T13:54:14-08:00

[agent:url_screenshotter] Located Chrome/Chromium binary at /Applications/Chromium.app/Contents/MacOS/Chromium
Targets    : 1
Threads    : 8
Ports      : 443
Output dir : .

[agent:tcp_port_scanner] Received new host: www.google.com
www.google.com port 443: open

Clustering similar sites... done
Generating HTML report...[agent:url_publisher] Received new open port on www.google.com: 443
[agent:url_requester] Received new URL https://www.google.com/
[http] 2018/11/19 13:54:14 HTTP Request: GET / HTTP/1.1
Host: www.google.com
Content-Type: application/json
Forwarded: for=2.52.84.178;proto=http;by=37.88.159.54
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Via: 1.1 108.67.250.226
X-Forwarded-For: 165.55.242.208

 done

Time:
 - Started at  : 2018-11-19T13:54:14-08:00
 - Finished at : 2018-11-19T13:54:14-08:00
 - Duration    : 0s

Requests:
 - Successful : 0
 - Failed     : 0

 - 2xx : 0
 - 3xx : 0
 - 4xx : 0
 - 5xx : 0

Screenshots:
 - Successful : 0
 - Failed     : 0

Wrote HTML report to: aquatone_report.html

**echo "www.google.com" | aquatone -ports small**

quatone v1.4.1 started at 2018-11-19T13:56:16-08:00

Targets    : 1
Threads    : 8
Ports      : 80, 443
Output dir : .

www.google.com port 443: open
www.google.com port 80: open

Clustering similar sites... done
Generating HTML report... done

Time:
 - Started at  : 2018-11-19T13:56:16-08:00
 - Finished at : 2018-11-19T13:56:16-08:00
 - Duration    : 0s

Requests:
 - Successful : 0
 - Failed     : 0

 - 2xx : 0
 - 3xx : 0
 - 4xx : 0
 - 5xx : 0

Screenshots:
 - Successful : 0
 - Failed     : 0

Wrote HTML report to: aquatone_report.html

**Comment by lazydruidr** [comment]
Great thanks!

**Comment by michenriksen** [comment]
I have added a small delay in [1.4.2](https://github.com/michenriksen/aquatone/releases/tag/v1.4.2).

**Comment by gh0stkey** [comment]
This bug also exists in the latest version.
