### ISSUE TITLE
Idea : CIDR ranges

### ISSUE THREAD

**Issue by 0xc0ffeee** [michenriksen/aquatone#140]
It would be cool to feed IP CIDRs to aquatone. A good use case would be finding an organization's ASN and feeding the ip ranges to aquatone.

Thanks for your great work btw!

**Comment by michenriksen** [comment]
Aquatone doesn't understand CIDRs "out of the box" but with the help of other tools, it's pretty easy to make Aquatone scan a CIDR. [prips](https://devel.ringlet.net/sysutils/prips/) is a tool you can use for this:

    $ prips 64.4.246.0/24 | aquatone

You can also scan the range with nmap or masscan for http ports and feed Aquatone the XML report:

    $ cat scan.xml | aquatone -nmap
