### ISSUE TITLE
NMAP parsing seems to be broken

### ISSUE THREAD

**Issue by awhitehatter** [michenriksen/aquatone#146]
Running `./aquatone -nmap output.xml -out screens` appears to just sit there. Even with the debug flag, all I get is: 
```
aquatone v1.4.2 started at 2018-12-03T18:41:23Z

An older version of Chromium is installed. Screenshotting of HTTPS URLs might be unreliable.
```
The xml contains about 26 hosts, so nothing crazy large.

**Comment by michenriksen** [comment]
aquatone works by piping content into the tool, so try it like this:

    $ cat output.xml | aquatone -nmap -out screens

The `-nmap` flag tells aquatone to expect the data from `STDIN` to be an nmap/masscan xml file.

**Comment by awhitehatter** [comment]
D'oh! User error, my apologies! Thanks, dude. Pretty cool tool, I'm testing replacing httpscreenshot in my workflow with this, appreciate your efforts!

**Comment by michenriksen** [comment]
Sounds good! Let me know if you think something is missing. :)
