### ISSUE TITLE
Errno::EBADF: Bad file descriptor @ rb_io_set_nonblock <STDIN>

### ISSUE THREAD

**Issue by akkatracker** [michenriksen/aquatone#15]
![clipboard01](https://user-images.githubusercontent.com/2032746/27464300-f902b85a-580f-11e7-8711-4e369e6d56b4.png)

Apologies if this is a trivial error on my behalf (I don't normally play with Ruby) - but when running the sample usage (from Phase 1 on your blog) - on corp.yahoo.com I get this error. 

Does anyone know what is going on?

**Comment by michenriksen** [comment]
I don't know quite what is happening, but I can capture and handle the `Errno::EBADF` exception to prevent it from erroring out like that. I would also strongly suggest running AQUATONE in a [Kali linux](https://kali.org/) virtual machine. I think you will have a better experience with that. :)

**Comment by akkatracker** [comment]
Will do - that was my next course of action 

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by michenriksen** [comment]
This is issue is fixed in version 0.2.0.

**Comment by akkatracker** [comment]
@michenriksen confirmed working on my Windows environment now. 

Thanks
