### ISSUE TITLE
how to use in windows

### ISSUE THREAD

**Issue by jayateertha043** [michenriksen/aquatone#150]
neep help in windows usage i have installed it but how do i use it?
This is what i get when i use aquatone:

C:\Go\bin>aquatone
aquatone v1.4.2 started at 2018-12-11T14:39:18+05:30

Using unreliable Google Chrome for screenshots. Install Chromium for better results.

**Comment by michenriksen** [comment]
Please read the README. You need to pipe data from a file or command into aquatone.
