### ISSUE TITLE
Outdated source of CSS in aquatone report

### ISSUE THREAD

**Issue by alexander-medved** [michenriksen/aquatone#155]
The source of stylesheet with used hash now unavailable.
Please, update the style version.

this one works perfect:
href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/darkly/bootstrap.min.css" 
integrity="sha384-w+yWASP3zYNxxvwoQBD5fUSc1tctKq4KUiZzxgkBSJACiUp+IbweVKvsEhMI+gz7"

**Comment by michenriksen** [comment]
Hi, thanks for reporting this! I removed the SRI attribute from the CSS resource. I expected it to not change out of nowhere but apparently it does change. Fixed in version [1.4.3](https://github.com/michenriksen/aquatone/releases/tag/v1.4.3)
