### ISSUE TITLE
Screenshot failing on remote Digital Ocean server

### ISSUE THREAD

**Issue by ta1bbty** [michenriksen/aquatone#160]
Hi @michenriksen ,
Great tool here :+1: , really thanks for taking the time to develop it.

I am facing difficulty getting screenshots on my digital ocean server for some reason it fails with 
```
http://www.google.com/: screenshot failed: exit status 127
https://www.google.com/: screenshot failed: exit status 127
```

I don't know whether it is some **x11** issue ( I don't have that knowledge, just read it in another issue, but that was for nightmarejs ) or something else altogether.

However, its working fine on my local machine but I would still like to get it working on my remote server.

![image](https://user-images.githubusercontent.com/45117337/51085956-35e7d680-1766-11e9-9aa2-3697aa638904.png)

Thanks and regards,
Temporarya

**Comment by ta1bbty** [comment]
Sorry, my bad.
I found that it was due to chrome not working , [this](https://stackoverflow.com/questions/1763156/127-return-code-from) helped me figure that out.

It was because x11 packages aren't installed by default on aws and other hosting providers, found similar problem listed for **puppeteer** and it's solution was to install some packages. It's [here](https://github.com/astefanutti/decktape/issues/126#issuecomment-346930449)
So, after installing some packages it got working.

```
apt-get install -yq --no-install-recommends libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3 
```
So, I am closing it.

Thanks once again @michenriksen for such a wonderful tool.

**Comment by dehinde007** [comment]
its chromium failing. Follow [here](https://itsfoss.com/install-chromium-ubuntu/) to install chromium on ubuntu VPS. Then specify --chrome-path "chromium-browser".
