### ISSUE TITLE
Add External Output Path as Environment variable

### ISSUE THREAD

**Issue by h-yde** [michenriksen/aquatone#162]
I think it would be a great feature to implement the output path as an environment variable rather than the command line. I know it wasn't publicly documented in the Ruby version, but I loved that feature and I would love to see it in the Go version as well.

**Comment by michenriksen** [comment]
Thanks for the suggestion. That should be doable. :)

**Comment by michenriksen** [comment]
This feature has been added to [v1.6.0](https://github.com/michenriksen/aquatone/releases/tag/v1.6.0)
