### ISSUE TITLE
Changed bash prompt

### ISSUE THREAD

**Issue by yildirimserkan** [michenriksen/aquatone#165]
Hi Michael

How to change your bash prompt. I saw in your blog. Like this. Sorry but i cant find anywhere. 

![b4a0ab29-eaa3-4e5a-b441-cdcea8158c99](https://user-images.githubusercontent.com/11732458/51680567-29c80880-1ff3-11e9-9681-376ad26db892.jpeg)

**Comment by BBerastegui** [comment]
Hi @yildirimserkan , you can find how to customize your prompt here: https://code.tutsplus.com/tutorials/how-to-customize-your-command-prompt--net-24083

Please refrain from using the repo for things like this, use Twitter or other means... this it's a little bit offtopic :)

Please close the issue so we don't overwhelm the author with such things. Cheers !
