### ISSUE TITLE
Aquatone seems to stop after the first host, and the first failure?

### ISSUE THREAD

**Issue by Viss** [michenriksen/aquatone#178]
Why would this happen?
It appears as though aquatone just gives up entirely after the first attempt of trying to hit the first host in the list. 

![image](https://user-images.githubusercontent.com/1756255/56085961-815f5e80-5e01-11e9-9db6-4cdb3ac81a00.png)

**Comment by michenriksen** [comment]
I could not replicate this issue with the latest version ([v1.6.0](https://github.com/michenriksen/aquatone/releases/tag/v1.6.0)). Could you try again with the latest version?

If you still experience problems, try to increase timeouts with the `-scan-timeout` and `-screenshot-timeout` flags.

**Comment by Viss** [comment]
running exactly the same command with the new version (1.6.0) seems to work just fine!
