### ISSUE TITLE
Ability to use or exclude collector   

### ISSUE THREAD

**Issue by s4ndeeps** [michenriksen/aquatone#18]
As we know aquatone using some great sources for fetching passive data and dictionary as well, so its some cases u dont need to get data from some selective sources for various regions, so it will good to add feature with option to use or exclude the collector while running scan! 

eg: ```aquatone-discover --domain test.com --exclude dictionary ```

**Comment by michenriksen** [comment]
Hi there, this is actually already implemented with the `--disable-collectors` option, which accepts a comma separated list of collector names/keys. You can find the collector keys by doing `aquatone-discover --list-collectors` 

**Example**

    $ aquatone-discover -d example.com --disable-collectors=shodan,dictionary,virustotal

There is also the `--only-collectors` option which also accepts a comma-separated list of collector keys, if you only want to run specific collectors.

**Comment by s4ndeeps** [comment]
Hey, that's great, as i was checking readme, these flags are mentioned nowhere if am not wrong, so it will be good if you can mention it somewhere.

**Comment by michenriksen** [comment]
See `aquatone-discover --help` ;)
