### ISSUE TITLE
[Request] Basic Authentication

### ISSUE THREAD

**Issue by hoddy** [michenriksen/aquatone#181]
I'm unable to add basic authentication to my hosts, for example:
User:pass@127.0.0.1
Is passed as 127.0.0.1, I think the clever work in getting aquatone to take multiple types of input is cleaning the basic authentication from the line. Any chance this feature could be added?

**Comment by michenriksen** [comment]
I think it should work if you give the targets as URLs (e.g. `http://user:pass@127.0.0.1/`) as the `user:pass@` portion is part of the URI scheme and not hostnames.
