### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by L-codes** [michenriksen/aquatone#182]
1. Will it be better to support the following format?
```
# Specify 443 port
echo google.com:443 | aquatone
```

2. aquatone_report.html preview add title
<img width="355" alt="image" src="https://user-images.githubusercontent.com/20529064/57349742-ca4ecc80-718d-11e9-988f-fb64552d6597.png">

**Comment by michenriksen** [comment]
Thanks for your suggestions!

The `google.com:443` specification would be a bit non-standard as port specification is not part of a hostname. It is however part of the URI specification, so it can be achieved by simply adding a scheme to the input like `https://google.com:<port>` and it should work just fine.

Adding a title to the report is a great idea! I am currently working on a refactoring to make the HTML report part of the tool better, and I will add page titles to the report data.
