### ISSUE TITLE
"net::ERR_INSUFFICIENT_RESOURCES" when loading a large report + pagination not working

### ISSUE THREAD

**Issue by eur0pa** [michenriksen/aquatone#187]
When loading a big (30MB in my case) aquatone report, the console will be spamming `net::ERR_INSUFFICIENT_RESOURCES` and the "Show More" button will be disabled, effectively rendering pagination unusable. I know this is anti-aesthetic but please let's keep it simple: can we get one HTML file every, say, 20 entries?

**Comment by michenriksen** [comment]
This sounds like a humongous report and amount of targets. I'm hesitant to change the new HTML report which I believe is very good for the "average" Aquatone session, when problems like this can be easily sorted by using standard bash commands like [split](https://manpages.ubuntu.com/manpages/bionic/man1/split.1.html) on the input being piped into Aquatone.
