### ISSUE TITLE
Feature: Screenshot URLS from urls.txt file without port knocking 

### ISSUE THREAD

**Issue by unl1k3ly** [michenriksen/aquatone#189]
Awesome work mate, as always! Legend!

Would be alright to somehow dont make aquatone to scan for new urls once we provide the full URL with the following port ? ie. https://secret.google.com:9001

Reason why I'm saying that, doing a raw xml from masscan/nmap can sometimes miss things due server_name just stuff, however, would be nice to use aquatone and its amazing screenshot and reporting js to just shoot a screenshot on a giving.

Hope it makes sense.

Cheers

**Comment by unl1k3ly** [comment]
nevermind ... it actually does just as that... i got confused because the "ports" menu banner still showing up when run as targets.txt
Cheers

**Comment by michenriksen** [comment]
Yeah, I can see why showing the port list would be confusing to see when it shouldn't be scanning any ports.

I will look into only showing the port list if it got any targets that need to undergo portscanning.
