### ISSUE TITLE
Can you integrate new api support zoomeye into aquatone tool ?

### ISSUE THREAD

**Issue by ismailtasdelen** [michenriksen/aquatone#190]
Hi @michenriksen,
 
Can you integrate new api support [ZoomEye](https://www.zoomeye.org/doc) into aquatone tool ?

I just wanted to give a new suggestion to change the tool. You can have more subdomains if you provide this api support.

Thanks

**Comment by michenriksen** [comment]
The current version no longer enumerates subdomains as other tools are now doing a better job at that. The old Ruby version is no longer maintained.
