### ISSUE TITLE
Got a problem! Only one url have been scanned

### ISSUE THREAD

**Issue by TerickJojo** [michenriksen/aquatone#191]
![image](https://user-images.githubusercontent.com/24235319/58851640-6d3d1e00-8648-11e9-8be7-bf418ebe067c.png)

Here is hosts.txt
![image](https://user-images.githubusercontent.com/24235319/58851756-d58bff80-8648-11e9-8ac6-d174c5ba07af.png)

**Comment by michenriksen** [comment]
It's hard for me to identify the problem with the host count when the hosts.txt file contents are blurred. A possible explanation could be that the file contains duplicate hosts which are de-duplicated by Aquatone when it extracts targets from the content.

As for the missing screenshots, try to increase timeouts with the `-scan-timeout` and `-screenshot-timeout` flags.

**Comment by TerickJojo** [comment]
Thank you so much. `-scan-timeout` solved the problem.

By the way, the default value of `-scan-timeout` is so low. Hope you can optimize it.

Thanks again.
