### ISSUE TITLE
Screenshot failed with Prebuild Version

### ISSUE THREAD

**Issue by fuuddanni** [michenriksen/aquatone#199]
Hi, is used your prebuild Version 1.7 and it doesnt work straight forward and don´t take any Screenshot Pictures. My System Setup has a running Go and also a Selenium Version.

How are the screenshots taken? Are there any libraries needed? I do not want switching to Chromium.

Thank you for your replay. Greetz
![auqatone](https://user-images.githubusercontent.com/6312269/61590198-541b0d00-abb5-11e9-9a57-8008a9248820.PNG)

**Comment by IAmStoxe** [comment]
I can second this. I have tried it with both of the most recent aquatone versions and both of the latest chrome drivers (and chrome itself). All fail with exit code 1 and no other information.

**Comment by raigorx** [comment]
Same here tested in both Chrome and Chromium

[aquatone_windows_amd64_1.7.0.zip
](https://github.com/michenriksen/aquatone/releases/download/v1.7.0/aquatone_windows_amd64_1.7.0.zip)

Windows 7 x64
Chrome: 76.0.3809.132 (Official Build) (64-bit)
Chromium: 79.0.3912.0 (Build for developers) (64 bits)

`[agent:url_screenshotter] Error: exit status 1
http://example.com/: screenshot timed out
[agent:url_screenshotter] Error: exit status 1
https://example.com/: screenshot timed out
`

**Comment by Ramzeth** [comment]
Had the same issue with Windows.

Ensure that you provided a full path to `-out ` parameter. 
Like that:
`type urls.txt | aquatone.exe -out c:\temp\aquatone\`

**Comment by fuuddanni** [comment]
Thank you Ramzeth, i gave it a try, but it also failed with exception error (runtime). I switched over to gowitness, an Eyewitness fork written in Golang which works perfectly: https://github.com/sensepost/gowitness
![exception](https://user-images.githubusercontent.com/6312269/66237987-c1d7cf00-e6f6-11e9-9481-08cfec123961.PNG)

**Comment by webx0** [comment]
> Thank you Ramzeth, i gave it a try, but it also failed with exception error (runtime). I switched over to gowitness, an Eyewitness fork written in Golang which works perfectly: https://github.com/sensepost/gowitness
> ![exception](https://user-images.githubusercontent.com/6312269/66237987-c1d7cf00-e6f6-11e9-9481-08cfec123961.PNG)

This worked for me, thanks.

**Comment by webx0** [comment]
> Had the same issue with Windows.
> 
> Ensure that you provided a full path to `-out ` parameter.
> Like that:
> `type urls.txt | aquatone.exe -out c:\temp\aquatone\`

This worked for me, thanks.

**Comment by ethicalhackingplayground** [comment]
Chromium had issues so I installed. `man` and `gdb` 

```sudo apt-get install man```
```sudo apt-get install gdb```

**Comment by UWA-Nigel** [comment]
> Had the same issue with Windows.
> 
> Ensure that you provided a full path to `-out ` parameter.
> Like that:
> `type urls.txt | aquatone.exe -out c:\temp\aquatone\`

I was having screenshot issues in Windows, seems like the compiled .exe doesn't look at the working directory when it runs the screenshot.

**Comment by kiyell** [comment]
> Had the same issue with Windows.
> 
> Ensure that you provided a full path to `-out ` parameter.
> Like that:
> `type urls.txt | aquatone.exe -out c:\temp\aquatone\`

This also worked for me. Thank you.

**Comment by 99smith** [comment]
Had the same issue with Windows.

    Ensure that you provided a full path to -out parameter.
    Like that:
    type urls.txt | aquatone.exe -out c:\temp\aquatone\


------------------------------ This worked for me as well , whoever wrote this thank u million times
