### ISSUE TITLE
An unexpected error occurred: Errno::ENETUNREACH: Network is unreachable

### ISSUE THREAD

**Issue by naterobbified** [michenriksen/aquatone#2]
Hey there, sweet tool. Everything works fine during the Discovery portion, but I seem to be having trouble during the port scanning portion, as it errors out whenever I run it.  I've tried different switches to specify different ports but it always gives me the same error.

<img width="1156" alt="screen shot 2017-06-17 at 10 45 20 pm" src="https://user-images.githubusercontent.com/3721692/27258423-dd13ca40-53ae-11e7-876e-f543892b152b.png">

**Comment by michenriksen** [comment]
Thanks for reporting this. The fix was pretty simple, I pushed a new version which handles this exception. You can get it with `gem update aquatone`.
