### ISSUE TITLE
move /.aquatone/

### ISSUE THREAD

**Issue by random-robbie** [michenriksen/aquatone#21]
hey dude 

how can i move /.aquatone/ to /var/ww/html/.aquatone/ and have it still work?

**Comment by michenriksen** [comment]
Hey there, it's currently not a documented "feature", but when AQUATONE tries to determine the folder to write files to, it will first look for an environment variable called `AQUATONEPATH` before falling back to the default location of `~/aquatone`.

You can either define this environment variable somewhere like your `.bashrc` file, like:

    export AQUATONEPATH="/var/www/html/.aquatone/"

Or you can prepend it before the aquatone commands, if it's more of a one-off thing:

    $ AQUATONEPATH="/var/www/html/.aquatone/" aquatone-discover -d example.com
    $ AQUATONEPATH="/var/www/html/.aquatone/" aquatone-scan -d example.com
    $ AQUATONEPATH="/var/www/html/.aquatone/" aquatone-gather -d example.com

Hope that helps you, let me know if you have any problems.

**Comment by random-robbie** [comment]
thanks dude will deffo look doing this!
