### ISSUE TITLE
cannot call non-function xurls.Relaxed 

### ISSUE THREAD

**Issue by yuxiaokui** [michenriksen/aquatone#215]
go get github.com/michenriksen/aquatone

/root/go/pkg/mod/github.com/michenriksen/aquatone@v1.7.0/parsers/regex.go:22:39: cannot call non-function xurls.Relaxed (type *regexp.Regexp)

**Comment by yuxiaokui** [comment]
Ubuntu 没有这个问题。  忽略吧。

**Comment by chppppp** [comment]
what was your fix for this? thanks!

**Comment by HetVikam** [comment]
how to fix this?

**Comment by alegra8611** [comment]
Sorry for the late reply,

Issue is resolved with:

GO111MODULE=on go get github.com/shelld3v/aquatone

It is stated that go module support needs to be enabled for install
