### ISSUE TITLE
An unexpected error occurred: ChildProcess::Error: process not started

### ISSUE THREAD

**Issue by naterobbified** [michenriksen/aquatone#23]
When I run the gather command I receive the following error.

 <img width="838" alt="screen shot 2017-07-07 at 6 27 39 pm" src="https://user-images.githubusercontent.com/3721692/27981577-d0d9a4ae-6342-11e7-913b-b63e58b23d9a.png">

**Comment by random-robbie** [comment]
run xfvb-run -a before hand it's due to it being headless

**Comment by madaratech** [comment]
@random-robbie any requirement for using ` xfvb-run -a`? as i see the error while using it
````
-bash: xfvb-run: command not found
````

**Comment by cnbriggs** [comment]
The correct command is: `xvfb-run`
