### ISSUE TITLE
Discover Bulk Domains

### ISSUE THREAD

**Issue by bugtest0101** [michenriksen/aquatone#27]
Would it be possible to add an option to discover bulk domains?

**Comment by michenriksen** [comment]
Hi there, what are bulk domains?

**Comment by cnbriggs** [comment]
I would guess the request means allowing users to specify an input file with multiple domains to scan, rather than just a single domain with the "-d" switch.

**Comment by bugtest0101** [comment]
As @cnbriggs mentioned, a switch to accept multiple domains would be great!

**Comment by christophetd** [comment]
+1 for this suggestion! Any chance you'll implement that? Otherwise, would you be OK if I sent a PR for that @michenriksen?

**Comment by christophetd** [comment]
@michenriksen Any updates on that? Willing to send a PR.
