### ISSUE TITLE
Issue in " aquatone-gather -d domain.com "

### ISSUE THREAD

**Issue by testuser100101** [michenriksen/aquatone#28]
hey,
whenever i run **aquatone-gather -d domain.com**  i get the following error.

![aquatone](https://user-images.githubusercontent.com/30369893/28491127-d5888fd2-6ee2-11e7-81f9-0523a56f6b74.png)
but nodejs as you can see  is already installed : 
1 - 
![nodejs](https://user-images.githubusercontent.com/30369893/28491159-d5d2553a-6ee3-11e7-9043-d2fd609fb02e.png)

2 - ![whereisnodejs](https://user-images.githubusercontent.com/30369893/28491163-0555f460-6ee4-11e7-9f1c-f1771c133639.png)

how can i fix this ?
thanks

**Comment by michenriksen** [comment]
aquatone-gather is checking if the `node` executable is present, not `nodejs`. What do you get when doing `which node`?

**Comment by michenriksen** [comment]
It also looks like you have a **super** old version installed. You should probably update to make sure things will work.

**Comment by testuser100101** [comment]
i got `/usr/bin/node`

**Comment by cnbriggs** [comment]
Try following these steps to install Node.js 8: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by phspade** [comment]
![screenshot at 2017-07-31 19-20-52](https://user-images.githubusercontent.com/18681023/28775638-aaa2b1b8-7625-11e7-9d81-91277f9503f1.png)

**Comment by justpentest** [comment]
I solved the issue by downloading appropriate package from
https://docs.npmjs.com/getting-started/installing-node
It will give u node and npm executable
cp npm /usr/bin/
cp node /usr/bin/
Finally
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by j00tesiD** [comment]
@michenriksen How to fix it?
<img src="https://image.ibb.co/fSZr1G/Screenshot_2017_10_03_00_18_32.png" alt="Screenshot_2017_10_03_00_18_32" border="0">

**Comment by michenriksen** [comment]
Hi @j00tesiD, Sorry, I have decided to only support troubleshooting of problems in Kali linux, as all kinds of problems can happen with different operating systems and environments. AQUATONE should work fine on Kali Linux, so please try it out there and let me know if you still have problems.
