### ISSUE TITLE
Stuck at identifying nameservers

### ISSUE THREAD

**Issue by bibz0r** [michenriksen/aquatone#3]
`root@localhost:~# aquatone-discover --domain ..........at --threads 25
                           __
  ____ _____ ___  ______ _/ /_____  ____  ___
 / __ `/ __ `/ / / / __ `/ __/ __ \/ __ \/ _ \
/ /_/ / /_/ / /_/ / /_/ / /_/ /_/ / / / /  __/
\__,_/\__, /\__,_/\__,_/\__/\____/_/ /_/\___/
        /_/  discover v0.1.1 - by @michenriksen

Identifying nameservers for ........at...
`

Is it possible to enable some verbosity? I waited for like 5 minutes but nothing happened...

**Comment by bibz0r** [comment]
Didn't wait long enough. After about 10 minutes I got ".... has no nameservers"

**Comment by michenriksen** [comment]
Hmm, that sounds strange. Does normal `nslookup` commands take a long time on the machine you're running it on?

**Comment by warlock0007** [comment]
Hi, I was facing the same issue so I read the manual once again and implemented all the changes in command such as threads, fallback servers. But still its stuck at that stage. other network lookups are working fine. Any suggestions?
