### ISSUE TITLE
Wordlist for dictionary module in discover

### ISSUE THREAD

**Issue by dhauenstein** [michenriksen/aquatone#31]
Right now, a hardcoded wordlist file is used for the brute force/dict module. I'd love to specify my own wordlist file here. Is this in the planning? If I find the time I might file a PR the next days..

**Comment by michenriksen** [comment]
Yes, this feature is definitely on the TODO. I plan to make it so that collector modules can define and register their own command line options, where one of the options for the Dictionary collector will be a `--wordlist` option.

**Comment by michenriksen** [comment]
This has now been implemented in [version 4.0.4](https://github.com/michenriksen/aquatone/blob/master/CHANGELOG.md#040)

**Comment by dhauenstein** [comment]
Super awesome!
