### ISSUE TITLE
Censys and PassiveTotal Key

### ISSUE THREAD

**Issue by Teicu** [michenriksen/aquatone#32]
Hi again 

can you explain please how to add the API key to these services? 
 
as you know Censys have API ID and Secret
 
and PassiveTotal have Key and Secret, where the key is my email address 

Thank you

**Comment by michenriksen** [comment]
The key requirements for the Censys collector are: `censys_id` and `censys_secret`, so it would be:

    $ aquatone-discover --set-key censys_id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    $ aquatone-discover --set-key censys_secret xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Key requirements for PassiveTotal are: `passivetotal_key` and `passivetotal_secret`, so:

    $ aquatone-discover --set-key passivetotal_key youremail@example.com
    $ aquatone-discover --set-key passivetotal_secret xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
