### ISSUE TITLE
aquatone-gather

### ISSUE THREAD

**Issue by phspade** [michenriksen/aquatone#33]
i cant use this one although i have nodejs installed on my system.

![screenshot at 2017-07-30 09-51-35](https://user-images.githubusercontent.com/18681023/28749990-2b536f4c-750d-11e7-9280-916503e65182.png)

**Comment by phspade** [comment]
i solved it by installing nodejs-legacy.. however, i can't install the nightmare.js .. maybe i can install it manually.. can you help me?

**Comment by phspade** [comment]
![screenshot at 2017-07-30 12-15-30](https://user-images.githubusercontent.com/18681023/28750539-177af6c0-7521-11e7-8421-234623e5823c.png)

**Comment by random-robbie** [comment]
tried installing latest node?
```
#Install NodeJS
curl -sL https://deb.nodesource.com/setup_8.x | bash -
apt-get install -qq -y nodejs

``
