### ISSUE TITLE
 uninitialized constant Aquatone::Commands::Takeover (NameError)

### ISSUE THREAD

**Issue by smrk3r** [michenriksen/aquatone#34]
Ran gem update and am getting " uninitialized constant Aquatone::Commands::Takeover (NameError)" when running aquatone-takeover -d test.com.

`/usr/local/rvm/gems/ruby-1.9.3-p551/gems/aquatone-0.3.0/exe/aquatone-takeover:113:in `<top (required)>': uninitialized constant Aquatone::Commands::Takeover (NameError)
`

ideas?

**Comment by michenriksen** [comment]
Does it help if you `gem uninstall aquatone` and `gem install aquatone`?

**Comment by smrk3r** [comment]
Still getting the same error after an uninstall and install.

I was able to clone the repo fresh and `gem install aquatone` and it seems to have corrected the issue. Thanks!
