### ISSUE TITLE
i am getting error when i am using aquatone-gather

### ISSUE THREAD

**Issue by maheshtata2020** [michenriksen/aquatone#36]
<img width="570" alt="screen shot 2017-08-04 at 3 20 32 pm" src="https://user-images.githubusercontent.com/30227745/28964015-b9741500-7928-11e7-8808-266b90b40b32.png">

Hi

I am getting following error when i am running aquatone-gather. can you please help me in fixing this.

**Comment by michenriksen** [comment]
Please see last paragraph of the [Dependencies](https://github.com/michenriksen/aquatone#dependencies) section of the README.
