### ISSUE TITLE
Detection of wildcard domain resolutions

### ISSUE THREAD

**Issue by BBerastegui** [michenriksen/aquatone#37]
Hi !

I've been testing the tool, and the results are pretty amazing.

Today I saw that there is one situation where the tool gets a little bit "crazy".

This situation is when the subdomain being "discovered" has a subdomain resolution wildcard.

In my example, all the subdomains under _*.example.com_ where resolving to the same IP, leading aquatone to generate a huge list of "discovered" domains (which were not "really" there).

Maybe a specific function for this check can be done, where 3 random long strings are generated and checked as subdomains for resolution, and if both three resolutions end up in the same IP, stop bruteforcing subdomains under that domain?

Any idea on how to "solve" this scenario?

Thanks !

**Comment by michenriksen** [comment]
Hi there, thanks for reporting!

Wildcard domain detection and filtering is already implemented in aquatone-discover. If you point it at a wildcard domain, you should see output like this:

```
aquatone-discover -d wildcard.domain
                           __
  ____ _____ ___  ______ _/ /_____  ____  ___
 / __ `/ __ `/ / / / __ `/ __/ __ \/ __ \/ _ \
/ /_/ / /_/ / /_/ / /_/ / /_/ /_/ / / / /  __/
\__,_/\__, /\__,_/\__,_/\__/\____/_/ /_/\___/
        /_/  discover v0.4.0 - by @michenriksen

Identifying nameservers for wildcard.domain... Done
Using nameservers:

 - 13.37.13.17
 - 13.37.13.18
 - 13.37.13.19

Checking for wildcard DNS... Wildcard detected!
Identifying wildcard IPs... Done
Filtering out hosts resolving to wildcard IPs
. . .
```

I haven't experienced any problems yet with this myself, but there are probably a lot of funky DNS servers out there. Would care to share the domain with me for debugging purposes? You can find my email address in the footer at [michenriksen.com](http://michenriksen.com/).

Thanks!

**Comment by MikeRich88** [comment]
s.cdn13.com with the dictionary collector enabled is a big mess.

Doesn't seem like wildcard hosts filter thing is working at all for that domain

**Comment by michenriksen** [comment]
@MikeRich88 Wildcard detection works just fine for me with `s.cdn13.com`. I don't see any "big mess" here. If wildcard is detected, aquatone-discover will do 20 lookups of random subdomains to hopefully capture every dynamic wildcard responses, but maybe if you are unlucky that one of the wildcard IPs are not captured in this process, you might see some false-positives. If you see that, you can try to run the command again.
