### ISSUE TITLE
Make aquatone-takeover a stand-alone tool 

### ISSUE THREAD

**Issue by dhauenstein** [michenriksen/aquatone#38]
I love and use aquatone on a daily basis, but sometimes i would like to check for domain takeover flaws against an existing list of domains (not discovered with aquatone). Maybe it would make sense to extrude the takeover functionality into a stand-alone tool, accepting a list of domain names, since I really like the extensive list of vulnerable providers.

**Comment by michenriksen** [comment]
That's an interesting idea and probably wouldn't be too much work to implement. I'll look into it.

**Comment by dhauenstein** [comment]
Awesome. I had a look and thought it would be a 5-minute task, but the design is a bit more intertwined than i thought. Give me a shout if you need help on that.

**Comment by BBerastegui** [comment]
I came to this issue to suggest something similar, that is the option to add aquatone-takeover the option to get a filename of subdomains to be checked for takeover, instead of relaying only on the hosts.json file.
