### ISSUE TITLE
enumerates subdomains

### ISSUE THREAD

**Issue by lnkakalink** [michenriksen/aquatone#39]
Hi pls add enumerates subdomains 

Google, Yahoo, Bing, Baidu,  Ask,  Virustotal,  DNSdumpster, and ReverseDNS 

guys pls add you service

**Comment by michenriksen** [comment]
I'm not too fond of supporting search engine scraping as they need constant maintenance and you run into problems with CAPTCHA rate-limiting and such things. I also don't believe they really would reveal much more than the existing collectors. Virustotal and DNSdumpster are already implemented (DNSDumpster through HackerTarget which uses the same data set). Don't know what ReverseDNS is.
