### ISSUE TITLE
uninitialized constant IO::EAGAINWaitReadable

### ISSUE THREAD

**Issue by zryny4** [michenriksen/aquatone#4]
On CentOS7:
`Checking for wildcard DNS... Done

Running collector: DNSDB... Done (0 hosts)
Running collector: Netcraft... Done (0 hosts)
Running collector: Shodan... Skipped
 -> Key 'shodan' has not been set
Running collector: Google Transparency Report... Done (0 hosts)
Running collector: Dictionary... Done (8209 hosts)
Running collector: HackerTarget... Done (1 host)
Running collector: VirusTotal... Skipped
 -> Key 'virustotal' has not been set
Running collector: Threat Crowd... Done (0 hosts)

Resolving 8210 unique hosts...
An unexpected error occurred: NameError: uninitialized constant IO::EAGAINWaitReadable
/usr/local/share/gems/gems/aquatone-0.1.1/lib/aquatone/command.rb:119:in `rescue in asked_for_progress?'
/usr/local/share/gems/gems/aquatone-0.1.1/lib/aquatone/command.rb:115:in `asked_for_progress?'
/usr/local/share/gems/gems/aquatone-0.1.1/lib/aquatone/commands/discover.rb:100:in `block in resolve_hosts'
/usr/local/share/gems/gems/aquatone-0.1.1/lib/aquatone/commands/discover.rb:99:in `each'
/usr/local/share/gems/gems/aquatone-0.1.1/lib/aquatone/commands/discover.rb:99:in `resolve_hosts'
/usr/local/share/gems/gems/aquatone-0.1.1/lib/aquatone/commands/discover.rb:19:in `execute!'
/usr/local/share/gems/gems/aquatone-0.1.1/lib/aquatone/command.rb:10:in `run'
/usr/local/share/gems/gems/aquatone-0.1.1/exe/aquatone-discover:129:in `<top (required)>'
/usr/local/bin/aquatone-discover:23:in `load'
/usr/local/bin/aquatone-discover:23:in `<main>'
`

**Comment by LukasReschke** [comment]
This seems to be a bug in JRuby as per https://github.com/jruby/jruby/issues/3520

I fixed this on OS X 10.12 locally with installing a newer version of Ruby and JRuby and then reinstalling aquatone:

```
brew install jruby
brew install ruby
gem install aquatone
```

**Comment by michenriksen** [comment]
Version 0.2.0 now handles this error so that it doesn't crash if it happens.
