### ISSUE TITLE
Specify custom directory for output

### ISSUE THREAD

**Issue by h-yde** [michenriksen/aquatone#42]
I have been using aquatone a lot lately and I must say I absolutely love it. However, one issue I have with it is the output is sent to the aquatone folder in my home directory. Personally I like to keep my home folder as organized as possible to make finding what I need easier. It would be nice to be able to specify a custom directory for aquatone output, in my case I would like to send it to ~/SecurityResearch/aquatone.

**Comment by michenriksen** [comment]
It's not a documented feature, but aquatone will actually look for the `AQUATONE_PATH` environment variable and use that value if it's set, or fall back to the default `~/aquatone` path if it's not set.

If you do `export AQUATONE_PATH="~/SecurityResearch/aquatone"` in your terminal initialisation file, it should start saving stuff there instead.

**Comment by h-yde** [comment]
I added that to my ~/.zshrc and it still is only recognizing the folder in my home directory.

**Comment by michenriksen** [comment]
I'm sorry, it's `AQUATONEPATH`, not `AQUATONE_PATH`. Try that and see if things work.

**Comment by h-yde** [comment]
Works great, thank you friend. Aquatone has made my life so much easier, thanks for the release!

**Comment by lodi-g** [comment]
You should honestly put it in the README. Thanks. :+1:
