### ISSUE TITLE
Add DNS information to Aquatone-Gather

### ISSUE THREAD

**Issue by Rhynorater** [michenriksen/aquatone#44]
I think it'd be super useful to have the nslookup information for all the ip addresses in Aquatone-Gather output because sometimes domains are aliases of other domains. Also, sometimes the companies forget to cloudfront a domain and, now that you know the url structure they use for their, say, s3 instances, you can use that information to poke for other s3 instances behind their cloudfront domains. HackerTarget makes an API for this that would make it simplicity itself. Just a submit a get request to this url: http://api.hackertarget.com/dnslookup/?q=google.com where "google.com" is the domain you are resolving. It will return the nslookup information.  Then, just create a horizontal bar under your packet information in the aquatone-gather output and put the information there. 

The only problem I could see with this is hackertarget uses its own NS to look up the ip addresses and aquatone (brilliantly) finds the nameservers for the domains. There might be a discrepancy there, but I think something is better than nothing.

**Comment by michenriksen** [comment]
Thanks for the feedback! That is an interesting feature that I will consider. In the meantime, would a quick bash one-liner like this work for you?

```bash
cat ~/aquatone/example.com/hosts.txt | cut -d "," -f 1 | xargs -I % curl http://api.hackertarget.com/dnslookup/?q=%
```

**Comment by Rhynorater** [comment]
Absolutely! Thanks so much :)

Justin Gardner
President, CyberSecurity @ VCU
CyberSecurity Intern, Dominion Power
Cell: (804)912-4148

**Comment by michenriksen** [comment]
Just played with it a bit more. If you don't care about being passive, you can also use `dig` locally and get the same information with the benefit of being able to query the authoritative name server:

```bash
cat ~/aquatone/example.com/hosts.txt | cut -d "," -f 1 | xargs -I % dig +noall +answer % any @ns1.example.com
```

Cheers

**Comment by Rhynorater** [comment]
Nice! I'll be integrating this into scripts for sure. Thanks :)
