### ISSUE TITLE
Load resolvers from txt file instead of CLI. 

### ISSUE THREAD

**Issue by menzow** [michenriksen/aquatone#46]
Hey,

I was wondering if there's any plans to allow loading dns resolvers from a text file instead of the CLI. A similar feature is being used by https://github.com/TheRook/subbrute and helps speeding up the recon process a lot.

Feel free to use my [resolvers.txt](https://github.com/michenriksen/aquatone/files/1304196/resolvers.txt). I've compiled the list today and it has around ~16k entries with 95% ~ 100% availability. A great source for fresh resolvers is: https://public-dns.info

**Comment by michenriksen** [comment]
Hi there, thanks for the feedback. That is a very interesting feature. Just to make sure I understand, you would want to have a flag like `--nameserver-file` which contains addresses for DNS servers which aquatone-discover would load in, and shuffle DNS requests between the nameservers to avoid rate-limiting and so on?

**Comment by menzow** [comment]
Yes that is exactly right. `subbrute` advices to have at least 16 resolvers per thread. Would love to make a PR for this but I don't have any ruby experience. Could give it a try if you have some sort of guide on which structure to use. 👍
