### ISSUE TITLE
Google Transparency Report Error

### ISSUE THREAD

**Issue by aliveli49** [michenriksen/aquatone#47]
Hi
When I discover domain, GTR gives an error like;
![image](https://user-images.githubusercontent.com/24583651/30735652-7173e290-9f88-11e7-9248-eda6527a74f2.png)

**Comment by michenriksen** [comment]
Hi there, thanks for reporting! Looks like Google has changed something around GTR that I need to adapt to. I'll push out a fix ASAP.

**Comment by michenriksen** [comment]
Luckily turned out to be an easy fix. The collector works again in version [0.4.1](https://github.com/michenriksen/aquatone/blob/master/CHANGELOG.md#041). You can get the new version by running `gem update aquatone`

**Comment by aliveli49** [comment]
It is OK, thank you.
