### ISSUE TITLE
An unexpected error occurred: Resolv::ResolvError: DNS result has no information for <unresolvable domain>

### ISSUE THREAD

**Issue by C8H10N4OO** [michenriksen/aquatone#5]
Hey nice work!

So looks like I'm running into a bunch of unhandled exceptions for DNS entries that don't resolve on this particular domain. They have a messy environment, so makes sense.  It errored on a variety of sub-domain entries, not just one.  Tried the `--ignore-private` flag as well. How about an `--ignore-errors` flag? Thoughts?

```
Identifying nameservers for xxxx.com ... An unexpected error occurred: Resolv::ResolvError: DNS result has no information for xxxx.domain.local
C:/Ruby24-x64/lib/ruby/2.4.0/resolv.rb:384:in `getaddress'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/lib/aquatone/domain.rb:20:in `block (2 levels) in nameservers'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/lib/aquatone/domain.rb:20:in `map'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/lib/aquatone/domain.rb:20:in `block in nameservers'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/lib/aquatone/domain.rb:16:in `times'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/lib/aquatone/domain.rb:16:in `nameservers'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/lib/aquatone/commands/discover.rb:33:in `setup_resolver'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/lib/aquatone/commands/discover.rb:16:in `execute!'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/lib/aquatone/command.rb:10:in `run'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/aquatone-0.1.1/exe/aquatone-discover:129:in `<top (required)>'
C:/Ruby24-x64/bin/aquatone-discover:22:in `load'
C:/Ruby24-x64/bin/aquatone-discover:22:in `<main>'
```

**Comment by bluedangerforyou** [comment]
i am having this issue as well, just installed newest version

Identifying nameservers for llmhq.com... An unexpected error occurred: Resolv::ResolvError: DNS result has no information for adc01.***.com
C:/Ruby31-x64/lib/ruby/3.1.0/resolv.rb:379:in `getaddress'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/lib/aquatone/domain.rb:20:in `block (2 levels) in nameservers'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/lib/aquatone/domain.rb:20:in `map'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/lib/aquatone/domain.rb:20:in `block in nameservers'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/lib/aquatone/domain.rb:16:in `times'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/lib/aquatone/domain.rb:16:in `nameservers'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/lib/aquatone/commands/discover.rb:33:in `setup_resolver'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/lib/aquatone/commands/discover.rb:16:in `execute!'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/lib/aquatone/command.rb:10:in `run'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/aquatone-0.5.0/exe/aquatone-discover:138:in `<top (required)>'
C:/Ruby31-x64/bin/aquatone-discover:32:in `load'
C:/Ruby31-x64/bin/aquatone-discover:32:in `<main>'
