### ISSUE TITLE
Error on API Keys handover

### ISSUE THREAD

**Issue by M3m0r3X** [michenriksen/aquatone#52]
Hi,

when I try to handover my Shodan API Key i get following error:

aquatone-discover --set-key shodan o1hyw8pv59vSVjrZU3Qaz6ZQqgM91ihQ
/var/lib/gems/2.3.0/gems/aquatone-0.4.1/lib/aquatone/key_store.rb:67:in `deserialize': undefined method `to_ruby' for false:FalseClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/aquatone-0.4.1/lib/aquatone/key_store.rb:37:in `read_key_store_file'
	from /var/lib/gems/2.3.0/gems/aquatone-0.4.1/lib/aquatone/key_store.rb:21:in `keys'
	from /var/lib/gems/2.3.0/gems/aquatone-0.4.1/lib/aquatone/key_store.rb:15:in `set'
	from /var/lib/gems/2.3.0/gems/aquatone-0.4.1/exe/aquatone-discover:63:in `block (2 levels) in <top (required)>'
	from /usr/lib/ruby/2.3.0/optparse.rb:1547:in `block in parse_in_order'
	from /usr/lib/ruby/2.3.0/optparse.rb:1534:in `catch'
	from /usr/lib/ruby/2.3.0/optparse.rb:1534:in `parse_in_order'
	from /usr/lib/ruby/2.3.0/optparse.rb:1528:in `order!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1620:in `permute!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1642:in `parse!'
	from /var/lib/gems/2.3.0/gems/aquatone-0.4.1/exe/aquatone-discover:136:in `<top (required)>'
	from /usr/local/bin/aquatone-discover:22:in `load'
	from /usr/local/bin/aquatone-discover:22:in `<main>'

Is there properly a missing dependency or is something wrong with the code. I run aquatone on a up to date kali box. I hope someone can help to solve this issue. Perhaps it is something simple...

The discovery run on a domain seems to work pretty good. I only  get the error by running the --set-key option as shown above. 

grettings 
m3m

**Comment by michenriksen** [comment]
Hi there, I don't know what the problem is exactly, but it might be because of a funky `.keys.yml` file. What happens if you do `mv ~/aquatone/.keys.yml ~/aquatone/.keys.yml.bak` and try to set the key again?

**Comment by M3m0r3X** [comment]
Hi,

thanks for our replay. Deleting the file solved the problem. Shame on me.... As I mentioned above it was just something stupid simple....

BTW: Aquatone is really a super tool. Thank you for this!

**Comment by michenriksen** [comment]
Great to hear that your problem got solved, and thanks for the kind words!
