### ISSUE TITLE
Nightmarejs must be run on a system with a graphical desktop session (X11)

### ISSUE THREAD

**Issue by vipinshady** [michenriksen/aquatone#55]
Few days back it was working fine on Kali Linux but now i guess after updating to 0.5 i'm getting this error "Nightmarejs must be run on a system with a graphical desktop session (X11)" please help me out.

**Comment by random-robbie** [comment]
you need to use xvfb-run 
for a bash script and install command.
https://gist.github.com/random-robbie/beae1991e9ad139c6168c385d8a31f7d

**Comment by alldayi420** [comment]
having same issue did what robbie said did not work/help or change anything...so what does this mean?...i have to install x11?>??im using kali linux
 xvfb-run???what is that ?
im using tool called sniper....

Wrote open ports to file:///root/aquatone/farmersonly.com/open_ports.txt
Wrote URLs to file:///root/aquatone/farmersonly.com/urls.txt
                           __
  ____ _____ ___  ______ _/ /_____  ____  ___
 / __ `/ __ `/ / / / __ `/ __/ __ \/ __ \/ _ \
/ /_/ / /_/ / /_/ / /_/ / /_/ /_/ / / / /  __/
\__,_/\__, /\__,_/\__,_/\__/\____/_/ /_/\___/
        /_/  gather v0.5.0 - by @michenriksen

Processing 20 pages...

Incompatability Error: Nightmarejs must be run on a system with a graphical desktop session (X11)
====================================================================================
 STARTING PUBLIC S3 BUCKET SCAN

**Comment by Gam-7** [comment]
the fix suggested by @random-robbie worked

**Comment by ojaschauhan44** [comment]
no it didnt work for me.. @Gam-7 ... can you explain what you did?

i am using kali linux and the error is still there for me.. cant find a way out

**Comment by 007sharky** [comment]
I have installed aquatone from "gem" and downloaded aquatone zip as described in https://github.com/michenriksen/aquatone/ -----> Readme.md. Now I use the zip extracted aquatone script for screenshots and the "gem" aquatone tools ----> aquatone-discover, aquatone-scan and aquatone-takeover for getting other informations

Now everything works well
