### ISSUE TITLE
Feature request: aquatone-gather arbitrary input

### ISSUE THREAD

**Issue by Viss** [michenriksen/aquatone#56]
I've been using aquatone for a while now and I really like the tool!
One of my workflows involves taking hosts from shodan (usually in the thousands) and performing some kind of enumeration on them. It would be super amazing if the gather component of aquatone could take a textfile, of something like host:port as a tasklist for screenshotting. Perhaps the addition of a '-f or --file' input arg to specify some sort of format of input file for processing?

**Comment by michenriksen** [comment]
Hi @Viss, this is definitely a feature I'm planning on implementing. Generally I want the different tools to be a bit more flexible than they are now. Until then, I think you can accomplish screenshotting of arbitrary `host:port`'s with Eyewitness, but I'm sure you know that.
