### ISSUE TITLE
False positives for cloudfront subdomain takeover

### ISSUE THREAD

**Issue by streaak** [michenriksen/aquatone#58]
Most of the time aquatone returns false positives while checking for subdomains pointing to Cloudfront. I believe the root cause for this issue is aquatone checks only HTTP version of the subdomain and not HTTPS. In the case of Cloudfront, both HTTP and HTTPS should show "Bad request" for a successful subdomain takeover.

**Comment by ramimac** [comment]
If you can give an example domain I may be able to create a patch

**Comment by streaak** [comment]
http://documents.uber.com/

**Comment by michenriksen** [comment]
Thank you very much for reporting and providing the information! @ramimac, are you up for tackling this?

**Comment by ramimac** [comment]
@michenriksen Happy to, should have a pull request in by EOD

**Comment by ramimac** [comment]
submitted the pull for the trivial fix, I was seeing the false positive however @streaak  so cant confirm

**Comment by streaak** [comment]
Can't wait 😃

**Comment by fbl4kd43m0n** [comment]
I got 2 false positives too

**Comment by ramimac** [comment]
@fbl4kd43m0n I've had an open PR fixing this since october, feel free to pull the branch

**Comment by fbl4kd43m0n** [comment]
thank you @ramimac
