### ISSUE TITLE
PTRArchive returned unexpected response code

### ISSUE THREAD

**Issue by madaratech** [michenriksen/aquatone#59]
![image](https://user-images.githubusercontent.com/8293321/31231843-a5c9d63a-aa05-11e7-802a-0303f70e39cb.png)

Not sure if PTRArchive  is blocking aquatone but if its same even sublister was using this same resources and they started to show fake result for sublister.

Ref: https://github.com/aboul3la/Sublist3r/issues/86

**Comment by ramimac** [comment]
Just confirming that I'm seeing this behavior as well

**Comment by Viss** [comment]
Same here, and this is the result of a tcpdump...

![image](https://user-images.githubusercontent.com/1756255/31409117-a597137c-adbf-11e7-8951-0d20a1f7fff7.png)

**Comment by jolle** [comment]
I noticed this issue previously as well, but it seems like PTRArchive has fixed some things and the issue is gone now.

```
➜  ~ aquatone-discover --domain host.com --only-collectors ptrarchive
                           __
  ____ _____ ___  ______ _/ /_____  ____  ___
 / __ `/ __ `/ / / / __ `/ __/ __ \/ __ \/ _ \
/ /_/ / /_/ / /_/ / /_/ / /_/ /_/ / / / /  __/
\__,_/\__, /\__,_/\__,_/\__/\____/_/ /_/\___/
        /_/  discover v0.5.0 - by @michenriksen

Identifying nameservers for host.com... Done
Using nameservers:

 - xxx.xxx.xxx.xxx
 - xxx.xxx.xxx.xxx
 - xxx.xxx.xxx.xxx
 - xxx.xxx.xxx.xxx

Checking for wildcard DNS... Done

Running collector: PTRArchive... Done (170 hosts)

Resolving 176 unique hosts...
xxx.xxx.xxx.xxx      subdomain-1.host.com
xxx.xxx.xxx.xxx      subdomain-2.host.com
xxx.xxx.xxx.xxx      subdomain-3.host.com
.....
```

**Comment by MuhammadKhizerJaved** [comment]
Not Fixed? Still same Here!

**Comment by prial260** [comment]
Still facing :- 

PTRArchive... Error
 -> PTRArchive returned unexpected response code: 502
