### ISSUE TITLE
[Aquatone-Discover: Feature Request] Adding External Output Option

### ISSUE THREAD

**Issue by mazen160** [michenriksen/aquatone#67]
Hi Michael,

First of all, big fan of all your work, excellent job!

I'm writing you today to propose a small feature on Aquatone. By
default, Aquatone-Discover saves identified subdomains in
~/aquatone/(Domain)/hosts.(txt|json).

It would be great if there is an additional output argument for each
scan to save identified subdomains, in addition the default one. This
can be implemented as an optional argument.

--output /tmp/subdomains.txt

Where /tmp/subdomains.txt will hold newline-delimited list of
identified subdomains.

This would help in automating Aquatone-Discover with additional scripts.
The default option is quite fine, but being able to make an external
copy is vital for scripting.

I'm looking forward to hear your opinion. Thank you very much again for
your excellent work!

**Comment by sa7mon** [comment]
I would also love to get this. I've just been `mv`ing the hosts.txt file for each domain to another location/name.
