### ISSUE TITLE
Feature request: Add an option to include our own wordlist

### ISSUE THREAD

**Issue by streaak** [michenriksen/aquatone#69]
Hey,
Just a simple feature request to add our own wordlist to aquatone-discover as it looks like I missed a lot of attack area cuz the wordlist was too small.

**Comment by ViperBlackSkull** [comment]
You can already do so with the --wordlist flag

From the help
--wordlist WORDLIST          OPTIONAL: wordlist/dictionary file to use for subdomain bruteforcing

Hope that can help you.

**Comment by streaak** [comment]
Hey,
Thanks for this. I guess I missed this when I read the docs.
