### ISSUE TITLE
Set API key for VirusTotal / Shodan

### ISSUE THREAD

**Issue by tylerapplebaum** [michenriksen/aquatone#7]
Just wondering where this option is configured.

**Comment by xycloops123** [comment]
aquatone/lib/aquatone/collectors/shodan.rb

you can configure others as well in the collectors folder.

**Comment by tylerapplebaum** [comment]
What line in the whatever.rb file would I add my API key to?

**Comment by tylerapplebaum** [comment]
Never mind, just re-read the docs. 

aquatone-discover --set-key shodan o1hyw8pv59vSVjrZU3Qaz6ZQqgM91ihQ

**Comment by Banginpadr** [comment]
> Never mind, just re-read the docs.
> 
> aquatone-discover --set-key shodan o1hyw8pv59vSVjrZU3Qaz6ZQqgM91ihQ

hey can you please help me? this is my path for this repo but is not reading it. im using a mac. is this right? 
export PATH="/Users/banginpadr/go/bin:$PATH"
