### ISSUE TITLE
Adding custom requests headers

### ISSUE THREAD

**Issue by phackt** [michenriksen/aquatone#72]
Hello Michael,

I just would like to know if there is a simple way/option to add/update a request header. I think about the User-Agent but also i would like to add some others headers while scanning.

Thanks a lot,

**Comment by random-robbie** [comment]
if you look at aquatone.js this should give you all the headers you need to alter.

https://github.com/michenriksen/aquatone/blob/master/aquatone.js

**Comment by phackt** [comment]
Ok great thanks a lot Michael
