### ISSUE TITLE
could it suppot many domains at once?

### ISSUE THREAD

**Issue by notwhy** [michenriksen/aquatone#78]
cool tool but i have an issue
when test domain.com
it may have some other domain name
like 
domain-inc.com
domain.net
domains.com
etc
sorry for my poor english ：）

**Comment by random-robbie** [comment]
you can write a bash script to do that

**Comment by sa7mon** [comment]
I would also love for this to be a feature. Maybe `--domains` takes a text file of domains?

**Comment by notwhy** [comment]
still strongly recommended to add this function. 
though i have write a script to do this. but i think is too slowly.
