### ISSUE TITLE
JSON::ParserError: 740 when running aquatone-gather

### ISSUE THREAD

**Issue by pentester02** [michenriksen/aquatone#8]
$ aquatone-gather --domain fakedomainnamehere.com --threads=15

Output:
Failed: https://fakedomainnamehere.com/ (x.fakedomainnamehere.com) - JSON::ParserError: 740: unexpected token at ''

I've experienced this on a number of domains where the gather functionality does not work.

**Comment by michenriksen** [comment]
Hey @pentester02, have a look at issue #1 for a fix for this issue.
