### ISSUE TITLE
Nightmarejs must be run on a system with a graphical desktop session (X11) | In Kali Linux

### ISSUE THREAD

**Issue by MuhammadKhizerJaved** [michenriksen/aquatone#85]
Hey,

I was using this great tool from a long time but today as i setup a new Kali VM machine & installed all the required tools and after working with aquatone-gather and got stuck on the error "**Nightmarejs must be run on a system with a graphical desktop session (X11)**" I tried to resolve the issue by doing some google search but haven't got any way to patch it up! 

Not sure what i did I miss 🔢 sowritingg here maybe u can guide :(
![n](https://user-images.githubusercontent.com/20904313/36803783-6a9ad1f2-1cda-11e8-98aa-713098ef557b.PNG)

**Comment by jolle** [comment]
Possibly a duplicate of #63

**Comment by MuhammadKhizerJaved** [comment]
Yeh sorry i sort it out but forgot to close this issue

**Comment by Gam-7** [comment]
@MuhammadKhizerJaved how did you fix it ?

**Comment by benspring** [comment]
@MuhammadKhizerJaved  #2nd How did you fix this?

**Comment by ojaschauhan44** [comment]
@MuhammadKhizerJaved  i too want the solution for the same... How to fix it??

**Comment by madikijeevan** [comment]
@MuhammadKhizerJaved  I have the same issue. Can you please tell me how u solved it.
