### ISSUE TITLE
issue while setting keys

### ISSUE THREAD

**Issue by rudrasingh99** [michenriksen/aquatone#91]
Hey,

while i was trying to set keys i faced this Error.

/var/lib/gems/2.3.0/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:44:in `initialize': No such file or directory @ rb_sysopen - /home/bugdiscloseguy/aquatone/.keys.yml (Errno::ENOENT)
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:44:in `open'
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:44:in `write_key_store_file'
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/lib/aquatone/key_store.rb:17:in `set'
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/exe/aquatone-discover:63:in `block (2 levels) in <top (required)>'
	from /usr/lib/ruby/2.3.0/optparse.rb:1540:in `block in parse_in_order'
	from /usr/lib/ruby/2.3.0/optparse.rb:1527:in `catch'
	from /usr/lib/ruby/2.3.0/optparse.rb:1527:in `parse_in_order'
	from /usr/lib/ruby/2.3.0/optparse.rb:1521:in `order!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1613:in `permute!'
	from /usr/lib/ruby/2.3.0/optparse.rb:1635:in `parse!'
	from /var/lib/gems/2.3.0/gems/aquatone-0.5.0/exe/aquatone-discover:136:in `<top (required)>'
	from /usr/local/bin/aquatone-discover:23:in `load'
	from /usr/local/bin/aquatone-discover:23:in `<main>'
![screenshot from 2018-04-10 17-12-46](https://user-images.githubusercontent.com/25739971/38555050-4e44f6be-3cb4-11e8-8922-742df5009380.png)

Let me know 
Thanks

**Comment by jafoca** [comment]
I had the same, or a very similar, issue as this on a fresh install of Aquatone (via gem install aquatone). I found that the solution was running 

> aquatone-discover -d DOMAINNAME

first then trying to set keys...

**Comment by mikedamm** [comment]
@Gam-7 I had the same issue.  Attempting to set keys before running a discover results in trying to write to the keystore in a directory that does not exist.

**Comment by Lz1y** [comment]
try : mkdir ~/aquatone
