### ISSUE TITLE
Stuck at Checking for wildcard DNS... Issue

### ISSUE THREAD

**Issue by backd00r101** [michenriksen/aquatone#93]
whenever i run aquatone-discover on any domain i want it logs

Identifying nameservers for nextdoor.com... Done
[DOMAIN].com has no nameservers. Using fallback nameservers.

then it logs
Checking for wildcard DNS... 
and stops at it... it never logs or outputs anything after that even after ALOT of hours, any solution??????

**Comment by snyff** [comment]
Hi mate, 

I had the same issue, the problem comes from your version of Ruby. You need Ruby 2.x.x at least.

The current problem comes from: 
    * timeouts= doesn't exist in all version of Ruby for Resolv::DNS
    * the rescue block in the resolve method catch the undefined method and this causes the code to loop

@michenriksen: it may be worth adding what version of Ruby are supported in the README.md and limit the scope of the rescue in the resolve method.

**Comment by IrkenEngineer** [comment]
I've got the same issue. Tried on an Arch Linux VM and couldn't fix it with RVM. So I switched to a Kali VM, updated/upgraded to the latest version. Same issue there.

The ReadMe says, "You will also need a newer version of Ruby installed. If you plan to use AQUATONE in Kali Linux, you are already set up with this."

Not sure how to fix it.
