### ISSUE TITLE
Installing Nightmare.js package.. Failed

### ISSUE THREAD

**Issue by H4kim** [michenriksen/aquatone#95]
i have this probleme when i run the command : aquatone-gather --domain xxxx.com 
                           __

, and nightmare id already installed ! any solution please ?

![screenshot from 2018-05-15 14-49-31](https://user-images.githubusercontent.com/25650578/40060748-364ef51c-584f-11e8-955e-3a550f8bf57a.png)

**Comment by Gam-7** [comment]
did you look here ? https://github.com/michenriksen/aquatone/issues/55 I followed random robbie and it is now working for me. His instruction is here https://gist.github.com/random-robbie/beae1991e9ad139c6168c385d8a31f7d and solved my problem

**Comment by H4kim** [comment]
he means run this commande : 
DEBUG=nightmare xvfb-run -a aquatone-gather -d $1 --threads 10

instead of this one : 
aquatone-gather --domain xxxx.com
 ??

**Comment by H4kim** [comment]
i'm bad in english and ubuntu too .. can you give me the steps please ?

**Comment by Gam-7** [comment]
Yes but first do as is said here https://gist.github.com/random-robbie/beae1991e9ad139c6168c385d8a31f7d 

eg install those packages first  then run that command you only need to run it once but install those packages first

**Comment by H4kim** [comment]
Okk thank you brother

**Comment by masterroshi1** [comment]
Did this issue get fixed for anyone?

**Comment by AshKumar06** [comment]
Its still there , i tried that link and installed all the pakages but again the same issue.

**Comment by racterub** [comment]
Hi, I've identify the buggy code in the script, still testing
https://github.com/michenriksen/aquatone/blob/8d3496bc2f6b74a50103ab704071ece3058b8902/lib/aquatone/commands/gather.rb#L35-L39

**Comment by racterub** [comment]
This "may" fix the issue
Try to modify https://github.com/michenriksen/aquatone/blob/8d3496bc2f6b74a50103ab704071ece3058b8902/lib/aquatone/commands/gather.rb#L38
add sudo to it

But the issue is still open until project owner or contributor answer.

**Comment by calebwatt15** [comment]
This can happen as NPM will not install nightmare (or rather Electron, which Nightmare seems to require) as root. This can be gotten around by installing nightmare before running aquatone-gather, as follows:
`npm install nightmare --unsafe-perm=true`

Then running aquatone-gather again.

**Comment by steermaximus** [comment]
@calebwatt15 Did that worked for you?
