### ISSUE TITLE
Incompatability Error: Nightmarejs must be run on a system with a graphical desktop session (X11), even I use the xvfb-run

### ISSUE THREAD

**Issue by mendickxiao** [michenriksen/aquatone#97]
root@kali:~# xvfb-run aquatone-gather --domain vip.com
                           __
  ____ _____ ___  ______ _/ /_____  ____  ___
 / __ `/ __ `/ / / / __ `/ __/ __ \/ __ \/ _ \
/ /_/ / /_/ / /_/ / /_/ / /_/ /_/ / / / /  __/
\__,_/\__, /\__,_/\__,_/\__/\____/_/ /_/\___/
        /_/  gather v0.5.0 - by @michenriksen

Processing 475 pages...

Incompatability Error: Nightmarejs must be run on a system with a graphical desktop session (X11)

**Comment by mendickxiao** [comment]
Anyone can help for it?

**Comment by HankleHigh** [comment]
the same problem :(

**Comment by HenriqueMachado** [comment]
Same here.. aquatone run, and exit randomly with this same error.

**Comment by ojaschauhan44** [comment]
Still having the isuue. not able to use aquatone-gather ...

**Comment by dd404x** [comment]
Same here.. aquatone run, and exit randomly with this same error.

**Comment by HenriqueMachado** [comment]
HI, I've that this issue only occurs when you are running two or more aquatone instances.

**Comment by ojaschauhan44** [comment]
solved the problem. its with electrons postscript

use : --unsafe-perm=true --allow-root
while installing electron..

install nightmare manually by:
sudo npm install --save nightmare --unsafe-perm=true --allow-root

and you are good to go
